// 自动生成 by tools/gen.py，勿手改
#[cxx::bridge(namespace = "dtkrs")]
pub mod genffi {
    extern "C++" {
        include!("dtk_gen_shim.h");
        type QWidget;
        type DAbstractDialog;
        type DAccessibilityChecker;
        type DAlertControl;
        type DArrowButton;
        type DArrowLineDrawer;
        type DArrowRectangle;
        type DBackgroundGroup;
        type DBaseLine;
        type DBlurEffectWidget;
        type DCircleProgress;
        type DColoredProgressBar;
        type DComboBox;
        type DCrumbTextFormat;
        type DCrumbEdit;
        type DDrawer;
        type DDrawerGroup;
        type DFileChooserEdit;
        type DFileDialog;
        type DFontComboBox;
        type DGraphicsGlowEffect;
        type DHeaderLine;
        type DImageViewer;
        type DIpv4LineEdit;
        type DKeySequenceEdit;
        type DLineEdit;
        type DListView;
        type DLoadingIndicator;
        type DMPRISControl;
        type DPageIndicator;
        type DPasswordEdit;
        type DPictureSequenceView;
        type DPrintPreviewWidget;
        type DSearchComboBox;
        type DSearchEdit;
        type DSettingsDialog;
        type DSettingsWidgetFactory;
        type DShadowLine;
        type DSimpleListItem;
        type DSimpleListView;
        type DSizeModeHelper;
        type DSlider;
        type DSpinBox;
        type DDoubleSpinBox;
        type DSpinner;
        type DSwitchButton;
        type DSwitchLineExpand;
        type DTabletWindowOptionButton;
        type DTickEffect;
        type DTipLabel;
        type DTitlebarToolBaseInterface;
        type DTitleBarToolInterface;
        type DTitleBarSpacerInterface;
        type DTitlebarSettings;
        type DToolButton;
        type DWaterProgress;
        type DWindowCloseButton;
        type DWindowMaxButton;
        type DWindowMinButton;
        type DWindowOptionButton;
        type DWindowQuitFullButton;

        unsafe fn gen_d_abstract_dialog_new() -> *mut DAbstractDialog;
        unsafe fn gen_d_abstract_dialog_move_to_center(self_: *mut DAbstractDialog);
        unsafe fn gen_d_abstract_dialog_move_to_top_right(self_: *mut DAbstractDialog);
        unsafe fn gen_d_accessibility_checker_new() -> *mut DAccessibilityChecker;
        unsafe fn gen_d_accessibility_checker_check(self_: *mut DAccessibilityChecker) -> bool;
        unsafe fn gen_d_accessibility_checker_start(self_: *mut DAccessibilityChecker, msec: i32);
        unsafe fn gen_d_alert_control_set_alert(self_: *mut DAlertControl, isAlert: bool);
        unsafe fn gen_d_alert_control_is_alert(self_: *mut DAlertControl) -> bool;
        unsafe fn gen_d_alert_control_show_alert_message(self_: *mut DAlertControl, text: &str, duration: i32);
        unsafe fn gen_d_alert_control_hide_alert_message(self_: *mut DAlertControl);
        unsafe fn gen_d_arrow_button_new() -> *mut DArrowButton;
        unsafe fn gen_d_arrow_button_arrow_direction(self_: *mut DArrowButton) -> i32;
        unsafe fn gen_d_arrow_button_button_state(self_: *mut DArrowButton) -> i32;
        unsafe fn gen_d_arrow_line_drawer_new() -> *mut DArrowLineDrawer;
        unsafe fn gen_d_arrow_line_drawer_set_title(self_: *mut DArrowLineDrawer, title: &str);
        unsafe fn gen_d_arrow_line_drawer_set_expand(self_: *mut DArrowLineDrawer, value: bool);
        unsafe fn gen_d_arrow_rectangle_radius(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_radius_force_enabled(self_: *mut DArrowRectangle) -> bool;
        unsafe fn gen_d_arrow_rectangle_arrow_height(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_arrow_width(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_arrow_x(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_arrow_y(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_margin(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_border_width(self_: *mut DArrowRectangle) -> i32;
        unsafe fn gen_d_arrow_rectangle_set_radius(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_radius_force_enable(self_: *mut DArrowRectangle, enable: bool);
        unsafe fn gen_d_arrow_rectangle_set_arrow_height(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_arrow_width(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_arrow_x(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_arrow_y(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_margin(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_border_width(self_: *mut DArrowRectangle, borderWidth: i32);
        unsafe fn gen_d_arrow_rectangle_set_width(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_set_height(self_: *mut DArrowRectangle, value: i32);
        unsafe fn gen_d_arrow_rectangle_show(self_: *mut DArrowRectangle, x: i32, y: i32);
        unsafe fn gen_d_arrow_rectangle_get_content(self_: *mut DArrowRectangle) -> *mut QWidget;
        unsafe fn gen_d_arrow_rectangle_resize_with_content(self_: *mut DArrowRectangle);
        unsafe fn gen_d_arrow_rectangle_move_(self_: *mut DArrowRectangle, x: i32, y: i32);
        unsafe fn gen_d_arrow_rectangle_shadow_x_offset(self_: *mut DArrowRectangle) -> f64;
        unsafe fn gen_d_arrow_rectangle_shadow_y_offset(self_: *mut DArrowRectangle) -> f64;
        unsafe fn gen_d_arrow_rectangle_shadow_blur_radius(self_: *mut DArrowRectangle) -> f64;
        unsafe fn gen_d_arrow_rectangle_set_shadow_blur_radius(self_: *mut DArrowRectangle, shadowBlurRadius: f64);
        unsafe fn gen_d_arrow_rectangle_set_shadow_x_offset(self_: *mut DArrowRectangle, shadowXOffset: f64);
        unsafe fn gen_d_arrow_rectangle_set_shadow_y_offset(self_: *mut DArrowRectangle, shadowYOffset: f64);
        unsafe fn gen_d_arrow_rectangle_set_left_right_radius(self_: *mut DArrowRectangle, enable: bool);
        unsafe fn gen_d_arrow_rectangle_set_radius_arrow_style_enable(self_: *mut DArrowRectangle, enable: bool);
        unsafe fn gen_d_background_group_new() -> *mut DBackgroundGroup;
        unsafe fn gen_d_background_group_use_widget_background(self_: *mut DBackgroundGroup) -> bool;
        unsafe fn gen_d_background_group_set_item_spacing(self_: *mut DBackgroundGroup, spacing: i32);
        unsafe fn gen_d_background_group_set_use_widget_background(self_: *mut DBackgroundGroup, useWidgetBackground: bool);
        unsafe fn gen_d_base_line_new() -> *mut DBaseLine;
        unsafe fn gen_d_base_line_set_left_margin(self_: *mut DBaseLine, margin: i32);
        unsafe fn gen_d_base_line_set_right_margin(self_: *mut DBaseLine, margin: i32);
        unsafe fn gen_d_base_line_left_margin(self_: *mut DBaseLine) -> i32;
        unsafe fn gen_d_base_line_right_margin(self_: *mut DBaseLine) -> i32;
        unsafe fn gen_d_blur_effect_widget_new() -> *mut DBlurEffectWidget;
        unsafe fn gen_d_blur_effect_widget_radius(self_: *mut DBlurEffectWidget) -> i32;
        unsafe fn gen_d_blur_effect_widget_blur_rect_x_radius(self_: *mut DBlurEffectWidget) -> i32;
        unsafe fn gen_d_blur_effect_widget_blur_rect_y_radius(self_: *mut DBlurEffectWidget) -> i32;
        unsafe fn gen_d_blur_effect_widget_is_full(self_: *mut DBlurEffectWidget) -> bool;
        unsafe fn gen_d_blur_effect_widget_blur_enabled(self_: *mut DBlurEffectWidget) -> bool;
        unsafe fn gen_d_blur_effect_widget_mask_alpha(self_: *mut DBlurEffectWidget) -> u8;
        unsafe fn gen_d_blur_effect_widget_set_radius(self_: *mut DBlurEffectWidget, radius: i32);
        unsafe fn gen_d_blur_effect_widget_set_blur_rect_x_radius(self_: *mut DBlurEffectWidget, blurRectXRadius: i32);
        unsafe fn gen_d_blur_effect_widget_set_blur_rect_y_radius(self_: *mut DBlurEffectWidget, blurRectYRadius: i32);
        unsafe fn gen_d_blur_effect_widget_set_mask_alpha(self_: *mut DBlurEffectWidget, alpha: u8);
        unsafe fn gen_d_blur_effect_widget_set_full(self_: *mut DBlurEffectWidget, full: bool);
        unsafe fn gen_d_blur_effect_widget_set_blur_enabled(self_: *mut DBlurEffectWidget, blurEnabled: bool);
        unsafe fn gen_d_circle_progress_new() -> *mut DCircleProgress;
        unsafe fn gen_d_circle_progress_value(self_: *mut DCircleProgress) -> i32;
        unsafe fn gen_d_circle_progress_set_value(self_: *mut DCircleProgress, value: i32);
        unsafe fn gen_d_circle_progress_text(self_: *mut DCircleProgress) -> String;
        unsafe fn gen_d_circle_progress_set_text(self_: *mut DCircleProgress, text: &str);
        unsafe fn gen_d_circle_progress_line_width(self_: *mut DCircleProgress) -> i32;
        unsafe fn gen_d_circle_progress_set_line_width(self_: *mut DCircleProgress, width: i32);
        unsafe fn gen_d_colored_progress_bar_new() -> *mut DColoredProgressBar;
        unsafe fn gen_d_colored_progress_bar_remove_threshold(self_: *mut DColoredProgressBar, threshold: i32);
        unsafe fn gen_d_combo_box_new() -> *mut DComboBox;
        unsafe fn gen_d_combo_box_show_popup(self_: *mut DComboBox);
        unsafe fn gen_d_crumb_text_format_new() -> *mut DCrumbTextFormat;
        unsafe fn gen_d_crumb_text_format_text(self_: *mut DCrumbTextFormat) -> String;
        unsafe fn gen_d_crumb_text_format_set_text(self_: *mut DCrumbTextFormat, text: &str);
        unsafe fn gen_d_crumb_text_format_background_radius(self_: *mut DCrumbTextFormat) -> i32;
        unsafe fn gen_d_crumb_text_format_set_background_radius(self_: *mut DCrumbTextFormat, radius: i32);
        unsafe fn gen_d_crumb_edit_new() -> *mut DCrumbEdit;
        unsafe fn gen_d_crumb_edit_insert_crumb(self_: *mut DCrumbEdit, text: &str, pos: i32) -> bool;
        unsafe fn gen_d_crumb_edit_append_crumb(self_: *mut DCrumbEdit, text: &str) -> bool;
        unsafe fn gen_d_crumb_edit_contain_crumb(self_: *mut DCrumbEdit, text: &str) -> bool;
        unsafe fn gen_d_crumb_edit_dual_click_make_crumb(self_: *mut DCrumbEdit) -> bool;
        unsafe fn gen_d_crumb_edit_crumb_read_only(self_: *mut DCrumbEdit) -> bool;
        unsafe fn gen_d_crumb_edit_crumb_radius(self_: *mut DCrumbEdit) -> i32;
        unsafe fn gen_d_crumb_edit_splitter(self_: *mut DCrumbEdit) -> String;
        unsafe fn gen_d_crumb_edit_set_crumb_read_only(self_: *mut DCrumbEdit, crumbReadOnly: bool);
        unsafe fn gen_d_crumb_edit_set_crumb_radius(self_: *mut DCrumbEdit, crumbRadius: i32);
        unsafe fn gen_d_crumb_edit_set_splitter(self_: *mut DCrumbEdit, splitter: &str);
        unsafe fn gen_d_crumb_edit_set_dual_click_make_crumb(self_: *mut DCrumbEdit, flag: bool);
        unsafe fn gen_d_drawer_new() -> *mut DDrawer;
        unsafe fn gen_d_drawer_get_content(self_: *mut DDrawer) -> *mut QWidget;
        unsafe fn gen_d_drawer_set_header_height(self_: *mut DDrawer, height: i32);
        unsafe fn gen_d_drawer_set_expand(self_: *mut DDrawer, value: bool);
        unsafe fn gen_d_drawer_expand(self_: *mut DDrawer) -> bool;
        unsafe fn gen_d_drawer_set_animation_duration(self_: *mut DDrawer, duration: i32);
        unsafe fn gen_d_drawer_set_separator_visible(self_: *mut DDrawer, arg: bool);
        unsafe fn gen_d_drawer_set_expanded_separator_visible(self_: *mut DDrawer, arg: bool);
        unsafe fn gen_d_drawer_group_new() -> *mut DDrawerGroup;
        unsafe fn gen_d_drawer_group_checked_expand(self_: *mut DDrawerGroup) -> *mut DDrawer;
        unsafe fn gen_d_drawer_group_expand(self_: *mut DDrawerGroup, id: i32) -> *mut DDrawer;
        unsafe fn gen_d_drawer_group_checked_id(self_: *mut DDrawerGroup) -> i32;
        unsafe fn gen_d_file_chooser_edit_new() -> *mut DFileChooserEdit;
        unsafe fn gen_d_file_chooser_edit_init_dialog(self_: *mut DFileChooserEdit);
        unsafe fn gen_d_file_dialog_add_line_edit(self_: *mut DFileDialog, text: &str);
        unsafe fn gen_d_file_dialog_set_allow_mixed_selection(self_: *mut DFileDialog, on: bool);
        unsafe fn gen_d_file_dialog_get_combo_box_value(self_: *mut DFileDialog, text: &str) -> String;
        unsafe fn gen_d_file_dialog_get_line_edit_value(self_: *mut DFileDialog, text: &str) -> String;
        unsafe fn gen_d_file_dialog_set_visible(self_: *mut DFileDialog, visible: bool);
        unsafe fn gen_d_font_combo_box_new() -> *mut DFontComboBox;
        unsafe fn gen_d_graphics_glow_effect_new() -> *mut DGraphicsGlowEffect;
        unsafe fn gen_d_header_line_new() -> *mut DHeaderLine;
        unsafe fn gen_d_header_line_set_title(self_: *mut DHeaderLine, title: &str);
        unsafe fn gen_d_header_line_title(self_: *mut DHeaderLine) -> String;
        unsafe fn gen_d_image_viewer_new() -> *mut DImageViewer;
        unsafe fn gen_d_image_viewer_file_name(self_: *mut DImageViewer) -> String;
        unsafe fn gen_d_image_viewer_set_file_name(self_: *mut DImageViewer, fileName: &str);
        unsafe fn gen_d_image_viewer_scale_factor(self_: *mut DImageViewer) -> f64;
        unsafe fn gen_d_image_viewer_set_scale_factor(self_: *mut DImageViewer, factor: f64);
        unsafe fn gen_d_image_viewer_scale_image(self_: *mut DImageViewer, factor: f64);
        unsafe fn gen_d_image_viewer_auto_fit_image(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_fit_to_widget(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_fit_normal_size(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_rotate_clockwise(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_rotate_counterclockwise(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_rotate_angle(self_: *mut DImageViewer) -> i32;
        unsafe fn gen_d_image_viewer_reset_rotate_angle(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_clear(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_center_on(self_: *mut DImageViewer, x: f64, y: f64);
        unsafe fn gen_d_image_viewer_begin_crop_image(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_end_crop_image(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_reset_crop_image(self_: *mut DImageViewer);
        unsafe fn gen_d_image_viewer_set_crop_aspect_ratio(self_: *mut DImageViewer, w: f64, h: f64);
        unsafe fn gen_d_ipv4_line_edit_new() -> *mut DIpv4LineEdit;
        unsafe fn gen_d_ipv4_line_edit_display_text(self_: *mut DIpv4LineEdit) -> String;
        unsafe fn gen_d_ipv4_line_edit_cursor_position(self_: *mut DIpv4LineEdit) -> i32;
        unsafe fn gen_d_ipv4_line_edit_has_acceptable_input(self_: *mut DIpv4LineEdit) -> bool;
        unsafe fn gen_d_ipv4_line_edit_is_read_only(self_: *mut DIpv4LineEdit) -> bool;
        unsafe fn gen_d_ipv4_line_edit_set_cursor_position(self_: *mut DIpv4LineEdit, cursorPosition: i32);
        unsafe fn gen_d_ipv4_line_edit_set_read_only(self_: *mut DIpv4LineEdit, readOnly: bool);
        unsafe fn gen_d_ipv4_line_edit_set_selection(self_: *mut DIpv4LineEdit, start: i32, length: i32);
        unsafe fn gen_d_ipv4_line_edit_select_all(self_: *mut DIpv4LineEdit);
        unsafe fn gen_d_key_sequence_edit_new() -> *mut DKeySequenceEdit;
        unsafe fn gen_d_key_sequence_edit_clear(self_: *mut DKeySequenceEdit);
        unsafe fn gen_d_line_edit_new() -> *mut DLineEdit;
        unsafe fn gen_d_line_edit_set_placeholder_text(self_: *mut DLineEdit, arg0: &str);
        unsafe fn gen_d_line_edit_set_alert(self_: *mut DLineEdit, isAlert: bool);
        unsafe fn gen_d_line_edit_is_alert(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_show_alert_message(self_: *mut DLineEdit, text: &str, duration: i32);
        unsafe fn gen_d_line_edit_hide_alert_message(self_: *mut DLineEdit);
        unsafe fn gen_d_line_edit_set_left_widgets_visible(self_: *mut DLineEdit, visible: bool);
        unsafe fn gen_d_line_edit_set_right_widgets_visible(self_: *mut DLineEdit, visible: bool);
        unsafe fn gen_d_line_edit_set_clear_button_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_line_edit_is_clear_button_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_text(self_: *mut DLineEdit, text: &str);
        unsafe fn gen_d_line_edit_text(self_: *mut DLineEdit) -> String;
        unsafe fn gen_d_line_edit_clear(self_: *mut DLineEdit);
        unsafe fn gen_d_line_edit_speech_to_text_is_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_speech_to_text_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_line_edit_text_to_speech_is_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_text_to_speech_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_line_edit_text_to_translate_is_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_text_to_translate_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_line_edit_copy_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_copy_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_line_edit_cut_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_cut_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_line_edit_paste_enabled(self_: *mut DLineEdit) -> bool;
        unsafe fn gen_d_line_edit_set_paste_enabled(self_: *mut DLineEdit, enable: bool);
        unsafe fn gen_d_list_view_new() -> *mut DListView;
        unsafe fn gen_d_list_view_get_header_widget(self_: *mut DListView, index: i32) -> *mut QWidget;
        unsafe fn gen_d_list_view_get_footer_widget(self_: *mut DListView, index: i32) -> *mut QWidget;
        unsafe fn gen_d_list_view_count(self_: *mut DListView) -> i32;
        unsafe fn gen_d_list_view_remove_item(self_: *mut DListView, index: i32) -> bool;
        unsafe fn gen_d_list_view_remove_items(self_: *mut DListView, index: i32, count: i32) -> bool;
        unsafe fn gen_d_list_view_remove_header_widget(self_: *mut DListView, index: i32);
        unsafe fn gen_d_list_view_take_header_widget(self_: *mut DListView, index: i32) -> *mut QWidget;
        unsafe fn gen_d_list_view_remove_footer_widget(self_: *mut DListView, index: i32);
        unsafe fn gen_d_list_view_take_footer_widget(self_: *mut DListView, index: i32) -> *mut QWidget;
        unsafe fn gen_d_list_view_set_item_spacing(self_: *mut DListView, spacing: i32);
        unsafe fn gen_d_list_view_set_item_radius(self_: *mut DListView, radius: i32);
        unsafe fn gen_d_loading_indicator_new() -> *mut DLoadingIndicator;
        unsafe fn gen_d_loading_indicator_loading(self_: *mut DLoadingIndicator) -> bool;
        unsafe fn gen_d_loading_indicator_widget_source(self_: *mut DLoadingIndicator) -> *mut QWidget;
        unsafe fn gen_d_loading_indicator_ani_duration(self_: *mut DLoadingIndicator) -> i32;
        unsafe fn gen_d_loading_indicator_smooth(self_: *mut DLoadingIndicator) -> bool;
        unsafe fn gen_d_loading_indicator_rotate(self_: *mut DLoadingIndicator) -> f64;
        unsafe fn gen_d_loading_indicator_start(self_: *mut DLoadingIndicator);
        unsafe fn gen_d_loading_indicator_stop(self_: *mut DLoadingIndicator);
        unsafe fn gen_d_loading_indicator_set_loading(self_: *mut DLoadingIndicator, flag: bool);
        unsafe fn gen_d_loading_indicator_set_ani_duration(self_: *mut DLoadingIndicator, msecs: i32);
        unsafe fn gen_d_loading_indicator_set_widget_source(self_: *mut DLoadingIndicator, widgetSource: *mut QWidget);
        unsafe fn gen_d_loading_indicator_set_smooth(self_: *mut DLoadingIndicator, smooth: bool);
        unsafe fn gen_d_m_p_r_i_s_control_new() -> *mut DMPRISControl;
        unsafe fn gen_d_m_p_r_i_s_control_is_working(self_: *mut DMPRISControl) -> bool;
        unsafe fn gen_d_m_p_r_i_s_control_set_picture_visible(self_: *mut DMPRISControl, visible: bool);
        unsafe fn gen_d_page_indicator_new() -> *mut DPageIndicator;
        unsafe fn gen_d_page_indicator_page_count(self_: *mut DPageIndicator) -> i32;
        unsafe fn gen_d_page_indicator_set_page_count(self_: *mut DPageIndicator, count: i32);
        unsafe fn gen_d_page_indicator_next_page(self_: *mut DPageIndicator);
        unsafe fn gen_d_page_indicator_previous_page(self_: *mut DPageIndicator);
        unsafe fn gen_d_page_indicator_set_current_page(self_: *mut DPageIndicator, index: i32);
        unsafe fn gen_d_page_indicator_current_page_index(self_: *mut DPageIndicator) -> i32;
        unsafe fn gen_d_page_indicator_point_radius(self_: *mut DPageIndicator) -> i32;
        unsafe fn gen_d_page_indicator_set_point_radius(self_: *mut DPageIndicator, size: i32);
        unsafe fn gen_d_page_indicator_secondary_point_radius(self_: *mut DPageIndicator) -> i32;
        unsafe fn gen_d_page_indicator_set_secondary_point_radius(self_: *mut DPageIndicator, size: i32);
        unsafe fn gen_d_page_indicator_point_distance(self_: *mut DPageIndicator) -> i32;
        unsafe fn gen_d_page_indicator_set_point_distance(self_: *mut DPageIndicator, distance: i32);
        unsafe fn gen_d_password_edit_new() -> *mut DPasswordEdit;
        unsafe fn gen_d_password_edit_is_echo_mode(self_: *mut DPasswordEdit) -> bool;
        unsafe fn gen_d_password_edit_set_echo_button_is_visible(self_: *mut DPasswordEdit, visible: bool);
        unsafe fn gen_d_password_edit_echo_button_is_visible(self_: *mut DPasswordEdit) -> bool;
        unsafe fn gen_d_picture_sequence_view_new() -> *mut DPictureSequenceView;
        unsafe fn gen_d_picture_sequence_view_play(self_: *mut DPictureSequenceView);
        unsafe fn gen_d_picture_sequence_view_pause(self_: *mut DPictureSequenceView);
        unsafe fn gen_d_picture_sequence_view_stop(self_: *mut DPictureSequenceView);
        unsafe fn gen_d_picture_sequence_view_speed(self_: *mut DPictureSequenceView) -> i32;
        unsafe fn gen_d_picture_sequence_view_set_speed(self_: *mut DPictureSequenceView, speed: i32);
        unsafe fn gen_d_picture_sequence_view_single_shot(self_: *mut DPictureSequenceView) -> bool;
        unsafe fn gen_d_picture_sequence_view_set_single_shot(self_: *mut DPictureSequenceView, singleShot: bool);
        unsafe fn gen_d_print_preview_widget_set_visible(self_: *mut DPrintPreviewWidget, visible: bool);
        unsafe fn gen_d_print_preview_widget_set_page_range(self_: *mut DPrintPreviewWidget, from: i32, to: i32);
        unsafe fn gen_d_print_preview_widget_set_page_range_a_l_l(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_pages_count(self_: *mut DPrintPreviewWidget) -> i32;
        unsafe fn gen_d_print_preview_widget_current_page(self_: *mut DPrintPreviewWidget) -> i32;
        unsafe fn gen_d_print_preview_widget_turn_page_able(self_: *mut DPrintPreviewWidget) -> bool;
        unsafe fn gen_d_print_preview_widget_set_scale(self_: *mut DPrintPreviewWidget, scale: f64);
        unsafe fn gen_d_print_preview_widget_get_scale(self_: *mut DPrintPreviewWidget) -> f64;
        unsafe fn gen_d_print_preview_widget_update_view(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_update_water_mark(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_refresh_begin(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_refresh_end(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_set_water_mark_type(self_: *mut DPrintPreviewWidget, type_: i32);
        unsafe fn gen_d_print_preview_widget_set_water_mark_rotate(self_: *mut DPrintPreviewWidget, rotate: f64);
        unsafe fn gen_d_print_preview_widget_set_water_mark_scale(self_: *mut DPrintPreviewWidget, scale: f64);
        unsafe fn gen_d_print_preview_widget_set_water_mark_opacity(self_: *mut DPrintPreviewWidget, opacity: f64);
        unsafe fn gen_d_print_preview_widget_set_confidential_water_mark(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_set_draft_water_mark(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_set_sample_water_mark(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_set_custom_water_mark(self_: *mut DPrintPreviewWidget, text: &str);
        unsafe fn gen_d_print_preview_widget_set_text_water_mark(self_: *mut DPrintPreviewWidget, text: &str);
        unsafe fn gen_d_print_preview_widget_set_water_mark_layout(self_: *mut DPrintPreviewWidget, layout: i32);
        unsafe fn gen_d_print_preview_widget_set_print_from_path(self_: *mut DPrintPreviewWidget, path: &str);
        unsafe fn gen_d_print_preview_widget_print_from_path(self_: *mut DPrintPreviewWidget) -> String;
        unsafe fn gen_d_print_preview_widget_set_asyn_preview(self_: *mut DPrintPreviewWidget, totalPage: i32);
        unsafe fn gen_d_print_preview_widget_is_asyn_preview(self_: *mut DPrintPreviewWidget) -> bool;
        unsafe fn gen_d_print_preview_widget_is_page_by_page(self_: *mut DPrintPreviewWidget, pageCopy: i32, isFirst: bool);
        unsafe fn gen_d_print_preview_widget_target_page_count(self_: *mut DPrintPreviewWidget, pageCount: i32) -> i32;
        unsafe fn gen_d_print_preview_widget_origin_page_count(self_: *mut DPrintPreviewWidget) -> i32;
        unsafe fn gen_d_print_preview_widget_printer_color_model(self_: *mut DPrintPreviewWidget) -> String;
        unsafe fn gen_d_print_preview_widget_update_preview(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_turn_front(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_turn_back(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_turn_begin(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_turn_end(self_: *mut DPrintPreviewWidget);
        unsafe fn gen_d_print_preview_widget_set_current_page(self_: *mut DPrintPreviewWidget, page: i32);
        unsafe fn gen_d_print_preview_widget_print(self_: *mut DPrintPreviewWidget, isSavedPicture: bool);
        unsafe fn gen_d_search_combo_box_new() -> *mut DSearchComboBox;
        unsafe fn gen_d_search_combo_box_set_editable(self_: *mut DSearchComboBox, editable: bool);
        unsafe fn gen_d_search_edit_new() -> *mut DSearchEdit;
        unsafe fn gen_d_search_edit_set_place_holder(self_: *mut DSearchEdit, placeHolder: &str);
        unsafe fn gen_d_search_edit_place_holder(self_: *mut DSearchEdit) -> String;
        unsafe fn gen_d_search_edit_clear(self_: *mut DSearchEdit);
        unsafe fn gen_d_search_edit_clear_edit(self_: *mut DSearchEdit);
        unsafe fn gen_d_search_edit_is_voice_input(self_: *mut DSearchEdit) -> bool;
        unsafe fn gen_d_search_edit_set_placeholder_text(self_: *mut DSearchEdit, text: &str);
        unsafe fn gen_d_search_edit_placeholder_text(self_: *mut DSearchEdit) -> String;
        unsafe fn gen_d_settings_dialog_new() -> *mut DSettingsDialog;
        unsafe fn gen_d_settings_dialog_widget_factory(self_: *mut DSettingsDialog) -> *mut DSettingsWidgetFactory;
        unsafe fn gen_d_settings_dialog_group_is_visible(self_: *mut DSettingsDialog, groupKey: &str) -> bool;
        unsafe fn gen_d_settings_dialog_set_reset_visible(self_: *mut DSettingsDialog, visible: bool);
        unsafe fn gen_d_settings_dialog_scroll_to_group(self_: *mut DSettingsDialog, groupKey: &str);
        unsafe fn gen_d_settings_dialog_set_group_visible(self_: *mut DSettingsDialog, groupKey: &str, visible: bool);
        unsafe fn gen_d_settings_widget_factory_new() -> *mut DSettingsWidgetFactory;
        unsafe fn gen_d_shadow_line_new() -> *mut DShadowLine;
        unsafe fn gen_d_simple_list_view_new() -> *mut DSimpleListView;
        unsafe fn gen_d_simple_list_view_set_row_height(self_: *mut DSimpleListView, height: i32);
        unsafe fn gen_d_simple_list_view_set_clip_radius(self_: *mut DSimpleListView, radius: i32);
        unsafe fn gen_d_simple_list_view_remove_item(self_: *mut DSimpleListView, item: *mut DSimpleListItem);
        unsafe fn gen_d_simple_list_view_clear_items(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_clear_selections(self_: *mut DSimpleListView, clearLastSelection: bool);
        unsafe fn gen_d_simple_list_view_search(self_: *mut DSimpleListView, searchContent: &str);
        unsafe fn gen_d_simple_list_view_set_single_select(self_: *mut DSimpleListView, singleSelect: bool);
        unsafe fn gen_d_simple_list_view_keep_select_when_click_blank(self_: *mut DSimpleListView, keep: bool);
        unsafe fn gen_d_simple_list_view_select_all_items(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_select_first_item(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_select_last_item(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_select_next_item(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_select_prev_item(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_shift_select_page_down(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_shift_select_page_up(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_shift_select_to_end(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_shift_select_to_home(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_shift_select_to_next(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_shift_select_to_prev(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_scroll_page_down(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_scroll_page_up(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_ctrl_scroll_page_down(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_ctrl_scroll_page_up(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_ctrl_scroll_to_end(self_: *mut DSimpleListView);
        unsafe fn gen_d_simple_list_view_ctrl_scroll_to_home(self_: *mut DSimpleListView);
        unsafe fn gen_d_slider_new() -> *mut DSlider;
        unsafe fn gen_d_slider_set_minimum(self_: *mut DSlider, min: i32);
        unsafe fn gen_d_slider_minimum(self_: *mut DSlider) -> i32;
        unsafe fn gen_d_slider_set_value(self_: *mut DSlider, value: i32);
        unsafe fn gen_d_slider_value(self_: *mut DSlider) -> i32;
        unsafe fn gen_d_slider_set_page_step(self_: *mut DSlider, pageStep: i32);
        unsafe fn gen_d_slider_page_step(self_: *mut DSlider) -> i32;
        unsafe fn gen_d_slider_set_maximum(self_: *mut DSlider, max: i32);
        unsafe fn gen_d_slider_maximum(self_: *mut DSlider) -> i32;
        unsafe fn gen_d_slider_set_mouse_wheel_enabled(self_: *mut DSlider, enabled: bool);
        unsafe fn gen_d_slider_set_tip_value(self_: *mut DSlider, value: &str);
        unsafe fn gen_d_slider_set_handle_visible(self_: *mut DSlider, b: bool);
        unsafe fn gen_d_slider_handle_visible(self_: *mut DSlider) -> bool;
        unsafe fn gen_d_slider_set_enabled_across_style(self_: *mut DSlider, enabled: bool);
        unsafe fn gen_d_spin_box_new() -> *mut DSpinBox;
        unsafe fn gen_d_spin_box_is_alert(self_: *mut DSpinBox) -> bool;
        unsafe fn gen_d_spin_box_show_alert_message(self_: *mut DSpinBox, text: &str, duration: i32);
        unsafe fn gen_d_spin_box_set_enabled_embed_style(self_: *mut DSpinBox, enabled: bool);
        unsafe fn gen_d_spin_box_set_alert(self_: *mut DSpinBox, alert: bool);
        unsafe fn gen_d_double_spin_box_new() -> *mut DDoubleSpinBox;
        unsafe fn gen_d_double_spin_box_is_alert(self_: *mut DDoubleSpinBox) -> bool;
        unsafe fn gen_d_double_spin_box_show_alert_message(self_: *mut DDoubleSpinBox, text: &str, duration: i32);
        unsafe fn gen_d_double_spin_box_set_enabled_embed_style(self_: *mut DDoubleSpinBox, enabled: bool);
        unsafe fn gen_d_double_spin_box_set_alert(self_: *mut DDoubleSpinBox, alert: bool);
        unsafe fn gen_d_spinner_new() -> *mut DSpinner;
        unsafe fn gen_d_spinner_is_playing(self_: *mut DSpinner) -> bool;
        unsafe fn gen_d_spinner_start(self_: *mut DSpinner);
        unsafe fn gen_d_spinner_stop(self_: *mut DSpinner);
        unsafe fn gen_d_switch_button_new() -> *mut DSwitchButton;
        unsafe fn gen_d_switch_line_expand_new() -> *mut DSwitchLineExpand;
        unsafe fn gen_d_switch_line_expand_set_title(self_: *mut DSwitchLineExpand, title: &str);
        unsafe fn gen_d_switch_line_expand_set_expand(self_: *mut DSwitchLineExpand, value: bool);
        unsafe fn gen_d_switch_line_expand_header(self_: *mut DSwitchLineExpand) -> *mut DBaseLine;
        unsafe fn gen_d_tablet_window_option_button_new() -> *mut DTabletWindowOptionButton;
        unsafe fn gen_d_tick_effect_play(self_: *mut DTickEffect);
        unsafe fn gen_d_tick_effect_stop(self_: *mut DTickEffect);
        unsafe fn gen_d_tick_effect_pause(self_: *mut DTickEffect);
        unsafe fn gen_d_tick_effect_resume(self_: *mut DTickEffect);
        unsafe fn gen_d_tick_effect_set_fixed_pixel_move(self_: *mut DTickEffect, pixel: i32);
        unsafe fn gen_d_tip_label_new() -> *mut DTipLabel;
        unsafe fn gen_d_titlebar_tool_base_interface_id(self_: *mut DTitlebarToolBaseInterface) -> String;
        unsafe fn gen_d_titlebar_tool_base_interface_description(self_: *mut DTitlebarToolBaseInterface) -> String;
        unsafe fn gen_d_titlebar_tool_base_interface_icon_name(self_: *mut DTitlebarToolBaseInterface) -> String;
        unsafe fn gen_d_title_bar_tool_interface_create_view(self_: *mut DTitleBarToolInterface) -> *mut QWidget;
        unsafe fn gen_d_title_bar_spacer_interface_create_placeholder_view(self_: *mut DTitleBarSpacerInterface) -> *mut QWidget;
        unsafe fn gen_d_title_bar_spacer_interface_size(self_: *mut DTitleBarSpacerInterface) -> i32;
        unsafe fn gen_d_titlebar_settings_tools_edit_panel(self_: *mut DTitlebarSettings) -> *mut QWidget;
        unsafe fn gen_d_tool_button_new() -> *mut DToolButton;
        unsafe fn gen_d_water_progress_new() -> *mut DWaterProgress;
        unsafe fn gen_d_water_progress_value(self_: *mut DWaterProgress) -> i32;
        unsafe fn gen_d_water_progress_start(self_: *mut DWaterProgress);
        unsafe fn gen_d_water_progress_stop(self_: *mut DWaterProgress);
        unsafe fn gen_d_water_progress_set_value(self_: *mut DWaterProgress, value: i32);
        unsafe fn gen_d_water_progress_set_text_visible(self_: *mut DWaterProgress, visible: bool);
        unsafe fn gen_d_window_close_button_new() -> *mut DWindowCloseButton;
        unsafe fn gen_d_window_max_button_new() -> *mut DWindowMaxButton;
        unsafe fn gen_d_window_max_button_is_maximized(self_: *mut DWindowMaxButton) -> bool;
        unsafe fn gen_d_window_max_button_set_maximized(self_: *mut DWindowMaxButton, isMaximized: bool);
        unsafe fn gen_d_window_min_button_new() -> *mut DWindowMinButton;
        unsafe fn gen_d_window_option_button_new() -> *mut DWindowOptionButton;
        unsafe fn gen_d_window_quit_full_button_new() -> *mut DWindowQuitFullButton;
    }
}
